version: '3'
services:
  elasticserach:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
    ports:
      - 9200:9200
    environment: 
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticserach:9200"
    depends_on: 
      - elasticserach